FROM golang:1.26-alpine

RUN apk add --no-cache git

RUN go install github.com/air-verse/air@v1.67.4

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]
